version: '3.8'

networks:
  mqtt_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.10.0/24

services:
  mqtt_broker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt_broker

    networks:
      mqtt_network:
        ipv4_address: 172.100.10.10

    volumes:
      - ./config:/mosquitto/config
      - ./log:/mosquitto/log
      - mosquitto_data:/mosquitto/data

    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host

volumes:
  mosquitto_data:
